language: node_js
node_js:
- '8'
before_script: yarn build
after_success: ./publish-examples.sh
deploy:
  provider: npm
  email: praneshpranesh@gmail.com
  api_key: $NPM_API_KEY
  skip_cleanup: true
  on:
    tags: true
    branch: master
